backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder_relative: true
media_folder: content/images
public_folder: /images

collections:
  - name: 'writing'
    label: 'Writing'
    folder: 'content/writing'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Image Credit', name: 'credit', widget: 'markdown', minimal: true }
      - { label: 'Post Body', name: 'body', widget: 'markdown' }
  - name: 'page-content'
    label: 'Custom Page Content'
    editor:
      preview: false
    files:
      - name: 'about'
        label: 'About Page'
        file: 'content/page-content/about.md'
        fields:
          - { label: 'Page Title', name: 'title', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'About Page Text', name: 'body', widget: 'markdown' }
      - name: 'welcome'
        label: 'Home Page Welcome Message'
        file: 'content/page-content/index.md'
        fields:
          - { label: 'Hero Image', name: 'image', widget: 'image' }
          - { label: 'Welcome Title', name: 'title', widget: 'string' }
          - { label: 'Welcome Text', name: 'body', widget: 'markdown' }
      - name: 'writing'
        label: 'Writing Page'
        file: 'content/page-content/writing.md'
        fields:
          - { label: 'Hero Image', name: 'image', widget: 'image' }
          - { label: 'Writing Page Title', name: 'title', widget: 'string' }
          - { label: 'Text Above Posts', name: 'body', widget: 'markdown' }
